[build]
buildAptPackages = ["libclang-dev", "clang", "pkg-config"]
buildCommand = "cargo build --release --package vaultrs-server"

[deploy]
aptPackages = ["ca-certificates"]
startCommand = "./target/release/vaultrs-server"
