[build]
buildAptPackages = ["libclang-dev", "clang", "pkg-config"]
buildCommand = "cargo install --path crates/vaultrs-server --root ."

[deploy]
aptPackages = ["ca-certificates"]
startCommand = "./bin/vaultrs-server"
