apiVersion: v2
name: zvault-operator
description: ZVault Kubernetes Operator â€” sync secrets from ZVault Cloud to K8s Secrets
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://zvault.cloud
sources:
  - https://github.com/ArcadeLabsInc/zvault
maintainers:
  - name: ZVault
    email: hello@zvault.cloud
    url: https://zvault.cloud
keywords:
  - secrets
  - vault
  - secrets-manager
  - security
